import mongoose from 'mongoose';
import BuyProperty from '../models/buyProperty';
import dotenv from 'dotenv';

dotenv.config();

const MONGODB_URI = process.env.MONGO_URI;

const buyProperties = [
  // Mumbai Properties
  {
    title: "Luxury 3 BHK Sea View Apartment",
    description: "Premium apartment with stunning sea views, modern amenities, and high-end finishes",
    price: 45000000,
    location: "Worli, Mumbai, Maharashtra",
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Parking", "Club House"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Lodha Group",
    reraId: "MH123456789",
    floorPlan: ["https://example.com/floorplan1.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Sea-Facing Penthouse in South Mumbai",
    description: "Luxurious penthouse with private terrace and panoramic views",
    price: 150000000,
    location: "Malabar Hill, Mumbai, Maharashtra",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 4500,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Private Pool", "Terrace Garden", "Private Elevator", "Smart Home"],
    yearBuilt: 2023,
    parkingSpaces: 4,
    propertyTax: 75000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Oberoi Realty",
    reraId: "MH987654321",
    floorPlan: ["https://example.com/floorplan2.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Bangalore Properties
  {
    title: "Modern Villa in Whitefield",
    description: "Contemporary villa with smart home features and sustainable design",
    price: 85000000,
    location: "Whitefield, Bangalore, Karnataka",
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Smart Home", "Solar Panels", "Garden", "Security"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 35000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Group",
    reraId: "KA123456789",
    floorPlan: ["https://example.com/floorplan3.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium 3 BHK in Electronic City",
    description: "Spacious apartment with modern amenities in tech hub",
    price: 32000000,
    location: "Electronic City, Bangalore, Karnataka",
    bedrooms: 3,
    bathrooms: 3,
    area: 1650,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 20000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Brigade Group",
    reraId: "KA987654321",
    floorPlan: ["https://example.com/floorplan4.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Delhi Properties
  {
    title: "Luxury House in Vasant Vihar",
    description: "Independent house with modern amenities and garden",
    price: 120000000,
    location: "Vasant Vihar, New Delhi, Delhi",
    bedrooms: 5,
    bathrooms: 5,
    area: 4000,
    propertyType: "House",
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde"],
    amenities: ["Garden", "Modular Kitchen", "Servant Quarter"],
    yearBuilt: 2021,
    parkingSpaces: 3,
    propertyTax: 50000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "DLF Limited",
    reraId: "DL123456789",
    floorPlan: ["https://example.com/floorplan5.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Hyderabad Properties
  {
    title: "Premium Villa in Gachibowli",
    description: "Luxurious villa in gated community with premium amenities",
    price: 65000000,
    location: "Gachibowli, Hyderabad, Telangana",
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b"],
    amenities: ["Swimming Pool", "Garden", "Club House"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 30000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS123456789",
    floorPlan: ["https://example.com/floorplan6.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Chennai Properties
  {
    title: "Sea View Apartment in ECR",
    description: "Premium apartment with sea view and modern amenities",
    price: 55000000,
    location: "ECR, Chennai, Tamil Nadu",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600573472550-8090b5e0745e"],
    amenities: ["Swimming Pool", "Gym", "Beach Access"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN123456789",
    floorPlan: ["https://example.com/floorplan7.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Additional Delhi Properties
  {
    title: "Modern Apartment in South Delhi",
    description: "Luxurious apartment with modern amenities in prime location",
    price: 85000000,
    location: "Greater Kailash, New Delhi, Delhi",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["Gym", "Swimming Pool", "24/7 Security", "Power Backup", "Club House"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 35000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "DLF Group",
    reraId: "DL987654321",
    floorPlan: ["https://example.com/floorplan8.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Villa in Chattarpur",
    description: "Spacious villa with garden and modern amenities",
    price: 150000000,
    location: "Chattarpur, New Delhi, Delhi",
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Servant Quarter", "Security"],
    yearBuilt: 2022,
    parkingSpaces: 4,
    propertyTax: 75000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Estates",
    reraId: "DL456789012",
    floorPlan: ["https://example.com/floorplan9.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Defence Colony",
    description: "Well-designed apartment with luxury finishes",
    price: 95000000,
    location: "Defence Colony, New Delhi, Delhi",
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Gym", "Club House", "Children's Play Area", "Garden"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 45000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Unity Group",
    reraId: "DL234567890",
    floorPlan: ["https://example.com/floorplan10.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Spacious House in Dwarka",
    description: "Beautiful house with modern architecture",
    price: 78000000,
    location: "Dwarka, New Delhi, Delhi",
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    propertyType: "House",
    images: ["https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b"],
    amenities: ["Modular Kitchen", "Power Backup", "Security", "Car Parking"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 38000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Godrej Properties",
    reraId: "DL345678901",
    floorPlan: ["https://example.com/floorplan11.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Penthouse in Rohini",
    description: "Exclusive penthouse with city views",
    price: 120000000,
    location: "Rohini, New Delhi, Delhi",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3800,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Terrace Garden", "Private Elevator", "Smart Home", "360° Views"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 60000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Supertech Limited",
    reraId: "DL567890123",
    floorPlan: ["https://example.com/floorplan12.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Additional Mumbai Properties
  {
    title: "Sea View Apartment in Bandra",
    description: "Premium apartment with stunning Arabian Sea views",
    price: 180000000,
    location: "Bandra West, Mumbai, Maharashtra",
    bedrooms: 4,
    bathrooms: 4,
    area: 2600,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d"],
    amenities: ["Sea View", "Gym", "Infinity Pool", "Concierge Service"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 85000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Lodha Group",
    reraId: "MH234567891",
    floorPlan: ["https://example.com/floorplan13.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Apartment in Juhu",
    description: "Beachside luxury apartment with premium amenities",
    price: 250000000,
    location: "Juhu, Mumbai, Maharashtra",
    bedrooms: 5,
    bathrooms: 5.5,
    area: 3500,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Beach Access", "Private Theater", "Spa", "Helipad Access"],
    yearBuilt: 2023,
    parkingSpaces: 4,
    propertyTax: 120000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Oberoi Realty",
    reraId: "MH345678912",
    floorPlan: ["https://example.com/floorplan14.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Apartment in Powai",
    description: "Contemporary apartment with lake views",
    price: 95000000,
    location: "Powai, Mumbai, Maharashtra",
    bedrooms: 3,
    bathrooms: 3,
    area: 1900,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Lake View", "Club House", "Gym", "Children's Play Area"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 45000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Hiranandani Developers",
    reraId: "MH456789123",
    floorPlan: ["https://example.com/floorplan15.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Villa in Andheri West",
    description: "Exclusive villa with premium finishes",
    price: 280000000,
    location: "Andheri West, Mumbai, Maharashtra",
    bedrooms: 6,
    bathrooms: 6.5,
    area: 5500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Staff Quarters"],
    yearBuilt: 2023,
    parkingSpaces: 5,
    propertyTax: 150000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Kalpataru Limited",
    reraId: "MH567891234",
    floorPlan: ["https://example.com/floorplan16.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Worli",
    description: "High-rise luxury apartment with city and sea views",
    price: 320000000,
    location: "Worli, Mumbai, Maharashtra",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["360° Views", "Private Elevator", "Smart Home", "Concierge"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 160000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Piramal Realty",
    reraId: "MH678912345",
    floorPlan: ["https://example.com/floorplan17.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Additional Bangalore Properties
  {
    title: "Luxury Penthouse in Indiranagar",
    description: "Exclusive penthouse with city views and premium amenities",
    price: 95000000,
    location: "Indiranagar, Bangalore, Karnataka",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3200,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Terrace Garden", "Private Elevator", "Smart Home", "360° Views"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 45000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Group",
    reraId: "KA234567890",
    floorPlan: ["https://example.com/floorplan18.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Apartment in Koramangala",
    description: "Contemporary apartment with modern amenities in tech hub",
    price: 45000000,
    location: "Koramangala, Bangalore, Karnataka",
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area", "Club House"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Brigade Group",
    reraId: "KA345678901",
    floorPlan: ["https://example.com/floorplan19.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Villa in Whitefield",
    description: "Spacious villa with premium finishes and modern amenities",
    price: 120000000,
    location: "Whitefield, Bangalore, Karnataka",
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Staff Quarters"],
    yearBuilt: 2023,
    parkingSpaces: 4,
    propertyTax: 60000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Group",
    reraId: "KA456789012",
    floorPlan: ["https://example.com/floorplan20.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Electronic City",
    description: "Well-designed apartment with modern amenities in tech hub",
    price: 35000000,
    location: "Electronic City, Bangalore, Karnataka",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area"],
    yearBuilt: 2022,
    parkingSpaces: 1,
    propertyTax: 20000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Brigade Group",
    reraId: "KA567890123",
    floorPlan: ["https://example.com/floorplan21.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Penthouse in Koramangala",
    description: "Exclusive penthouse with city views and premium amenities",
    price: 110000000,
    location: "Koramangala, Bangalore, Karnataka",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3500,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Terrace Garden", "Private Elevator", "Smart Home", "360° Views"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 55000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Group",
    reraId: "KA678901234",
    floorPlan: ["https://example.com/floorplan22.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Villa in Indiranagar",
    description: "Contemporary villa with smart home features and sustainable design",
    price: 130000000,
    location: "Indiranagar, Bangalore, Karnataka",
    bedrooms: 5,
    bathrooms: 5,
    area: 4000,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Smart Home", "Solar Panels", "Garden", "Security"],
    yearBuilt: 2023,
    parkingSpaces: 4,
    propertyTax: 65000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Prestige Group",
    reraId: "KA789012345",
    floorPlan: ["https://example.com/floorplan23.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Whitefield",
    description: "Spacious apartment with modern amenities in tech hub",
    price: 40000000,
    location: "Whitefield, Bangalore, Karnataka",
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 22000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Brigade Group",
    reraId: "KA890123456",
    floorPlan: ["https://example.com/floorplan24.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Additional Hyderabad Properties
  {
    title: "Luxury Apartment in Jubilee Hills",
    description: "Premium apartment with modern amenities in prime location",
    price: 75000000,
    location: "Jubilee Hills, Hyderabad, Telangana",
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["Gym", "Swimming Pool", "24/7 Security", "Power Backup", "Club House"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 35000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS234567890",
    floorPlan: ["https://example.com/floorplan25.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Villa in Banjara Hills",
    description: "Spacious villa with garden and modern amenities",
    price: 150000000,
    location: "Banjara Hills, Hyderabad, Telangana",
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Servant Quarter", "Security"],
    yearBuilt: 2022,
    parkingSpaces: 4,
    propertyTax: 75000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS345678901",
    floorPlan: ["https://example.com/floorplan26.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Hitech City",
    description: "Well-designed apartment with luxury finishes",
    price: 55000000,
    location: "Hitech City, Hyderabad, Telangana",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Gym", "Club House", "Children's Play Area", "Garden"],
    yearBuilt: 2023,
    parkingSpaces: 1,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS456789012",
    floorPlan: ["https://example.com/floorplan27.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Penthouse in Gachibowli",
    description: "Exclusive penthouse with city views",
    price: 120000000,
    location: "Gachibowli, Hyderabad, Telangana",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3800,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Terrace Garden", "Private Elevator", "Smart Home", "360° Views"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 60000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS567890123",
    floorPlan: ["https://example.com/floorplan28.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Apartment in Secunderabad",
    description: "Contemporary apartment with modern amenities",
    price: 45000000,
    location: "Secunderabad, Hyderabad, Telangana",
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area", "Club House"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS678901234",
    floorPlan: ["https://example.com/floorplan29.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Villa in Jubilee Hills",
    description: "Spacious villa with premium finishes and modern amenities",
    price: 180000000,
    location: "Jubilee Hills, Hyderabad, Telangana",
    bedrooms: 6,
    bathrooms: 6,
    area: 5000,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Staff Quarters"],
    yearBuilt: 2023,
    parkingSpaces: 5,
    propertyTax: 90000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS789012345",
    floorPlan: ["https://example.com/floorplan30.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Banjara Hills",
    description: "Well-designed apartment with luxury finishes",
    price: 65000000,
    location: "Banjara Hills, Hyderabad, Telangana",
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Gym", "Club House", "Children's Play Area", "Garden"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 35000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "Ramky Group",
    reraId: "TS890123456",
    floorPlan: ["https://example.com/floorplan31.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },

  // Additional Chennai Properties
  {
    title: "Luxury Apartment in Adyar",
    description: "Premium apartment with modern amenities in prime location",
    price: 65000000,
    location: "Adyar, Chennai, Tamil Nadu",
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c"],
    amenities: ["Gym", "Swimming Pool", "24/7 Security", "Power Backup", "Club House"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 35000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN234567890",
    floorPlan: ["https://example.com/floorplan32.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Villa in T Nagar",
    description: "Spacious villa with garden and modern amenities",
    price: 120000000,
    location: "T Nagar, Chennai, Tamil Nadu",
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Servant Quarter", "Security"],
    yearBuilt: 2022,
    parkingSpaces: 4,
    propertyTax: 60000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN345678901",
    floorPlan: ["https://example.com/floorplan33.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in Anna Nagar",
    description: "Well-designed apartment with luxury finishes",
    price: 55000000,
    location: "Anna Nagar, Chennai, Tamil Nadu",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Gym", "Club House", "Children's Play Area", "Garden"],
    yearBuilt: 2023,
    parkingSpaces: 1,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN456789012",
    floorPlan: ["https://example.com/floorplan34.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Penthouse in Mylapore",
    description: "Exclusive penthouse with city views",
    price: 110000000,
    location: "Mylapore, Chennai, Tamil Nadu",
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3500,
    propertyType: "Penthouse",
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498c"],
    amenities: ["Terrace Garden", "Private Elevator", "Smart Home", "360° Views"],
    yearBuilt: 2023,
    parkingSpaces: 3,
    propertyTax: 55000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN567890123",
    floorPlan: ["https://example.com/floorplan35.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Modern Apartment in Velachery",
    description: "Contemporary apartment with modern amenities",
    price: 45000000,
    location: "Velachery, Chennai, Tamil Nadu",
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d"],
    amenities: ["Gym", "Swimming Pool", "Children's Play Area", "Club House"],
    yearBuilt: 2022,
    parkingSpaces: 2,
    propertyTax: 25000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN678901234",
    floorPlan: ["https://example.com/floorplan36.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Luxury Villa in Adyar",
    description: "Spacious villa with premium finishes and modern amenities",
    price: 150000000,
    location: "Adyar, Chennai, Tamil Nadu",
    bedrooms: 6,
    bathrooms: 6,
    area: 5000,
    propertyType: "Villa",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9"],
    amenities: ["Private Pool", "Garden", "Home Theater", "Staff Quarters"],
    yearBuilt: 2023,
    parkingSpaces: 5,
    propertyTax: 75000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN789012345",
    floorPlan: ["https://example.com/floorplan37.jpg"],
    agentId: new mongoose.Types.ObjectId()
  },
  {
    title: "Premium Apartment in T Nagar",
    description: "Well-designed apartment with luxury finishes",
    price: 60000000,
    location: "T Nagar, Chennai, Tamil Nadu",
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    propertyType: "Apartment",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c"],
    amenities: ["Gym", "Club House", "Children's Play Area", "Garden"],
    yearBuilt: 2023,
    parkingSpaces: 2,
    propertyTax: 30000,
    constructionStatus: "ready",
    possession: new Date(),
    builder: "TVS Group",
    reraId: "TN890123456",
    floorPlan: ["https://example.com/floorplan38.jpg"],
    agentId: new mongoose.Types.ObjectId()
  }
];

async function seedBuyProperties() {
  try {
    if (!MONGODB_URI) {
      throw new Error('MONGO_URI is not defined in environment variables');
    }

    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing buy properties
    await BuyProperty.deleteMany({});
    console.log('Cleared existing buy properties');

    // Insert new properties
    const insertedProperties = await BuyProperty.insertMany(buyProperties);
    console.log(`Successfully inserted ${insertedProperties.length} properties`);

    console.log('Seeding completed successfully');
  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    await mongoose.connection.close();
    console.log('MongoDB connection closed');
  }
}

seedBuyProperties(); 